#!/bin/bash

PATH=/var/lib/gems/1.9.1/bin:/var/lib/gems/1.8/bin:/usr/local/bin:$PATH

models_dir=${1:-"/etc/backup/models"}

function log() {
    logger -t backup -i $@
}

for config_file in `/usr/bin/find $models_dir -maxdepth 1 -name '*.rb'`; do
    model=`basename $config_file .rb`
    log "Backup $model"
    nice -19 ionice -c3 backup perform -t $model -c $config_file -d /var/lib/backup/data -l /var/log --tmp-path=/tmp/ 2>&1 | \
        sed 's/^.*\] \(.*\)$/\1/' | log

    if [ $? == 0 ]; then
        log "Backup $model: done"
    else
        log "Backup $model: failed"
    fi
done
